micronaut:
  application:
    name: fretes

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

datasources:
  default:
    url: jdbc:mysql://localhost:3306/fretegrpc?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

endpoints:
  all:
    port: 8085
    sensitive: true
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
